cartshipping/cartapp/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *

urlpatterns = [
    path('',home,name='home'),
    path('add/', add_product, name='add_product'),
    path('list/', product_list, name='product_list'), 
    path('list2/', product_list2, name='product_list2'), 
    path('create_cart/', create_cart, name='create_cart'),
    path('delete_cart/', delete_cart, name='delete_cart'),
    path('add-to-cart/<str:type>/', add_to_cart, name='add_to_cart'),
    path('view-cart/', view_cart, name='view_cart'),
    path('order-confirmation/<int:order_id>/', order_confirmation, name='order_confirmation'),  # Update this line
    path('checkout/', checkout, name='checkout'), 
    path('place-order/', place_order, name='place_order'), 
    path('order-history/', order_history, name='order_history'),
    path('confirm_order/<int:order_id>/', confirm_order, name='confirm_order'),
    path('cart/delete/<int:product_id>/', delete_from_cart, name='delete_from_cart'),
]

cartshipping/cartshipping/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('cartapp.urls'))
]

cartshipping/cartapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=0)
    select = models.BooleanField(default=False)

    def __str__(self):
        return self.name
class Order(models.Model):
    #user = models.fogrekey(User,,,,,)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    confirmed = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=100,null=True)
    def __str__(self) -> str:
        return f'{self.ref_code} corfirmed {self.confirmed}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    products = models.ManyToManyField('Product')
    name= models.CharField(max_length=100,null=True)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

#ดู งง สร้างเป็น 2 ตัวเลยน่าจะง่ายกว่า oderitem

cartshipping/cartapp/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'quantity']

class ProductForm2(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'quantity']

class OrderConfirmationForm(forms.Form):
    confirm = forms.BooleanField(required=True)

cartshipping/cartapp/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.db import transaction
from .models import Order, OrderItem, Product
from decimal import Decimal
from .forms import *
from .generate_code import generate_random_system_code
from .clear_session import *
# Create your views here.
def home(req):
    key = check()
    #clear(key)
    return render(req,'cartapp/home.html',{})

def product_list(request):
    products = Product.objects.all()
    form = ProductForm2()
    return render(request, 'cartapp/product_list.html', {'products': products,
                                                         'form':form})
def product_list2(request):
    products = Product.objects.all()
    form = ProductForm2()
    return render(request, 'cartapp/product_list2.html', {'products': products,
                                                         'form':form})
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('product_list')  # Redirect to product list page
    else:
        form = ProductForm()

    return render(request, 'cartapp/add_product.html', {'form': form})

def create_cart(request):
    existing_order = Order.objects.filter(created_at__gte=timezone.now() - timezone.timedelta(minutes=10)).first()
    if existing_order:
        order = existing_order
        print(order)
    else:
        random_code = generate_random_system_code()
        order = Order.objects.create(total_price=Decimal('0.00'), ref_code=random_code)
        request.session['order'] = order.ref_code  # Use ref_code for session
        print(order, 'create cart done')
    return render(request, 'cartapp/view_cart.html', {'order': order})

def delete_cart(request):
    order_id = request.session.get('order')
    pop_order_id = request.session.pop('order', None)
    print('order id',order_id)
    if order_id:
        Order.objects.filter(ref_code=order_id).delete()
        print('deleted cart')
    return redirect('home')

def add_to_cart(request,type):
    if request.method == 'POST':
        
        if type=='type1':
            print('type1')
            product_ids = request.POST.getlist('product_id')
            quantities = request.POST.getlist('quantity')
            print('product_ids',product_ids)
            cart = request.session.get('cart', [])
            order_id = request.session.get('order')
            print('order_id',order_id)
            
            for product_id, quantity in zip(product_ids, quantities):
                print('in loop')
                print('product_id',product_id)
                p = Product.objects.all()
                for i in p:
                    print(i.id)
                product = get_object_or_404(Product, pk=product_id)
                print('fuck')
                quantity = int(quantity)  # Convert quantity to an integer

                # Check if the product is already in the cart
                existing_item = next((item for item in cart if item['id'] == product.id), None)
                print('fuck2')

                if existing_item:
                    print('fuck3')
                    # Update quantity if the product is already in the cart
                    existing_item['quantity'] += quantity
                else:
                    # Add a new item to the cart
                    cart.append({'id': product.id, 'name': product.name, 'price': str(product.price), 'quantity': quantity})
                    print('cart',cart)
                # Update order data in the database
                if not order_id:
                    random_code = generate_random_system_code()
                    order = Order.objects.create(total_price=Decimal('0.00'),ref_code=random_code)
        
                    print('created sussess')
                    request.session['order'] = random_code
                else:
                    print('orderlll')
                    order = get_object_or_404(Order, ref_code=order_id)


                order_item, created = OrderItem.objects.get_or_create(order=order, defaults={'quantity': 0, 'price': product.price})
                order_item.products.add(product)
                order_item.quantity = quantity
                order_item.save()

                order.total_price = (product.price * quantity)
                order.save()

            request.session['cart'] = cart
            print('.................')
            print(cart)
            return redirect('product_list')

        else:
            product_ids = request.POST.getlist('product_id')
            quantities = request.POST.getlist('quantity')
            checked_add = request.POST.getlist('add_to_cart')
            special = request.POST.get('special')
            order_id = request.session.get('order')

            # Filter the selected products based on 'add_to_cart' checkbox
            selected_product_ids = [product_id for product_id, checked in zip(product_ids, checked_add) if checked == 'checked']
            selected_products = Product.objects.filter(id__in=selected_product_ids)

            cart = request.session.get('cart', [])


            total_quantity = sum(int(quantity) for quantity in quantities)
            #print(total_quantity)

            if selected_products:
                with transaction.atomic():

                    if not order_id:
                        random_code = generate_random_system_code()
                        order = Order.objects.create(total_price=Decimal('0.00'),ref_code = random_code)
                        request.session['order'] = order.id
                    else:
                        order = get_object_or_404(Order, ref_code=order_id)


                    order_item = OrderItem.objects.create(order=order, quantity=total_quantity, price=0)
                    order_item.products.add(*selected_products)
                    order_item.price = sum(product.price for product in selected_products)
                    order_item.save()

                    # Update the order's total price
                    order.total_price += order_item.price
                    order.save()

                    # Update the cart with the selected products
                    for product in selected_products:
                        # Check if the product is already in the cart
                        existing_item = next((item for item in cart if item['id'] == product.id), None)

                        if existing_item:
                            # Update quantity if the product is already in the cart
                            existing_item['quantity'] += total_quantity
                        else:
                            # Add a new item to the cart
                            cart.append({'id': product.id, 'name': product.name, 'price': str(product.price), 'quantity': total_quantity})

                request.session['cart'] = cart

            return redirect('view_cart')

def view_cart(request):
    cart = request.session.get('cart', [])
    total_price = sum(Decimal(item['price']) * item.get('quantity', 1) for item in cart)  # Convert back to Decimal, and consider quantity
    items = []

    for item in cart:
        product = Product.objects.get(pk=item['id'])
        items.append({
            'id': item['id'],
            'name': item['name'],
            'price': Decimal(item['price']),
            'quantity': item.get('quantity', 1),
            'subtotal': Decimal(item['price']) * item.get('quantity', 1),
        })

    return render(request, 'cartapp/view_cart.html', {'items': items, 'total_price': total_price})

def delete_from_cart(request, product_id):
    product = get_object_or_404(OrderItem, products=product_id).first() # ปัญหาที่ database เพราะมันเป็น object เดียวกัน ต้องแยก
    print(product , 'delete done')
    product.delete()
    # Retrieve the current cart from the session
    cart = request.session.get('cart', [])

    # Remove the product from the cart if it exists
    cart = [item for item in cart if item['id'] != product_id]

    # Update the session with the modified cart
    request.session['cart'] = cart

    # Redirect back to the cart view
    return redirect('view_cart')

def checkout(request):
    order_id = request.session.get('order')
    if order_id:
        order = Order.objects.get(pk=order_id)
        order_items = OrderItem.objects.filter(order=order)
        return render(request, 'cartapp/checkout.html', {'order': order, 'order_items': order_items})
    else:
        return redirect('product_list')

def order_confirmation(request, order_id=None):
    if order_id is None:
        order_id = request.session.pop('order', None)
    if order_id:
        order = Order.objects.get(pk=order_id)
        order_items = OrderItem.objects.filter(order=order)
        return render(request, 'cartapp/order_confirmation.html', {'order': order, 'order_items': order_items})
    else:
        return redirect('product_list')

def place_order(request):
    order_id = request.session.pop('order', None)
    if order_id:
        # Process the order and update any necessary data (e.g., inventory, user information)

        # Clear the cart session
        request.session.pop('cart', None)

        return redirect('order_confirmation', order_id=order_id)
    else:
        return redirect('product_list')
    
def confirm_order(request, order_id):
    order = Order.objects.get(pk=order_id)

    if request.method == 'POST':
        form = OrderConfirmationForm(request.POST)
        if form.is_valid() and form.cleaned_data['confirm']:
            # Perform order confirmation logic here
            # For example, update order status, send confirmation emails, etc.
            order.confirmed = True
            order.save()
            return redirect('order_history')  # Redirect to a success page
    else:
        form = OrderConfirmationForm()

cartshipping/cartapp/templates/cartapp/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Add Product</h2>
    <form method="post" action="{% url 'add_product' %}">
      {% csrf_token %}
      {{ form.name.label_tag }} {{ form.name }}
      {{ form.description.label_tag }} {{ form.description }}
      {{ form.price.label_tag }} {{ form.price }}
      {{ form.quantity.label_tag }}
      <div class="quantity-control">
        <button type="button" onclick="decrementQuantity()">-</button>
        {{ form.quantity }}
        <button type="button" onclick="incrementQuantity()">+</button>
      </div>
      <button type="submit">Add Product</button>
    </form>
  
    <script>
      function incrementQuantity() {
        var quantityInput = document.getElementById("id_quantity");
        quantityInput.value = parseInt(quantityInput.value) + 1;
      }
  
      function decrementQuantity() {
        var quantityInput = document.getElementById("id_quantity");
        var currentQuantity = parseInt(quantityInput.value);
        quantityInput.value = currentQuantity > 0 ? currentQuantity - 1 : 0;
      }
    </script>
</html>

cartshipping/cartapp/templates/cartapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Your Project</title>
</head>
<body>

    <nav>
        <ul>
            <li><a href="{% url 'add_product' %}">Add Product</a></li>
            <li><a href="{% url 'product_list' %}">Product List</a></li>
        </ul>
    </nav>

    <div>
        {% block content %}{% endblock %}
    </div>

</body>
</html>

cartshipping/cartapp/templates/cartapp/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Checkout</h2>
    <p>Review your order before completing the checkout process:</p>
    <h3>Order Items:</h3>
    <ul>
      {% for item in order_items %}
        <li>{{ item.product.name }} - Quantity: {{ item.quantity }} - Price: {{ item.price }}</li>
      {% endfor %}
    </ul>
    <p>Total Price: {{ order.total_price }}</p>
    <form method="post" action="{% url 'place_order' %}">
      {% csrf_token %}
      <button type="submit">Place Order</button>
    </form>
    <p><a href="{% url 'view_cart' %}">Go Back to Cart</a></p>
</body>
</html>

cartshipping/cartapp/templates/cartapp/confirm_order.html
<h2>Confirm Order</h2>
<p>Order Details:</p>
<ul>
    {% for item in order.orderitem_set.all %}
        <li>{{ item.quantity }} x {{ item.product.name }} - ${{ item.price }}</li>
    {% endfor %}
</ul>
<p>Total Price: ${{ order.total_price }}</p>

<form method="post" action="{% url 'confirm_order' order.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm Order</button>
</form>

cartshipping/cartapp/templates/cartapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/create_cart/">create cart</a>
</body>
</html>

cartshipping/cartapp/templates/cartapp/order_confirmation.html
<h2>Order Confirmation</h2>
<p>Thank you for your order!</p>
<p>Order ID: {{ order.id }}</p>
<p>Total Price: {{ order.total_price }}</p>
<h3>Order Items:</h3>
<ul>
  {% for item in order_items %}
    <li>{{ item.product.name }} - Quantity: {{ item.quantity }} - Price: {{ item.price }}</li>
  {% endfor %}
</ul>
<p><a href="{% url 'product_list' %}">Continue Shopping</a></p>

cartshipping/cartapp/templates/cartapp/order_history.html
<h2>Order History</h2>
{% if user_orders %}
  <ul>
    {% for order in user_orders %}
      <li>
        Order ID: {{ order.id }} - Total Price: {{ order.total_price }} - Created at: {{ order.created_at }} cornfirmed: {{order.confirmed}}
        
        <ul>
          {% for item in order.orderitem_set.all %}
            <li>{{ item.product.name }} - Quantity: {{ item.quantity }} - Price: {{ item.price }}</li>
          {% endfor %}
        </ul>
        
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No orders found.</p>
{% endif %}
<p><a href="{% url 'product_list' %}">Back to Product List</a></p>

cartshipping/cartapp/templates/cartapp/order_placed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Order Placed</h2>
    <p>Your order (Order ID: {{ order_id }}) has been placed successfully!</p>
    <p>Thank you for shopping with us.</p>
    <p><a href="{% url 'product_list' %}">Continue Shopping</a></p>
</body>
</html>

cartshipping/cartapp/templates/cartapp/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Product List</h2>
    <ul>
      {% for product in products %}
        <li>
          {{ product.name }} - Quantity: {{ product.quantity }}
          <form class="add-to-cart-form" method="post" action="{% url 'add_to_cart' 'type1' %}">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}">
            <div class="quantity-control">
                <button type="button" onclick="decrementQuantity('{{ product.id }}')">-</button>
                <input type="number" name="quantity" id="id_quantity_{{ product.id }}" value="0" min="0">
                <button type="button" onclick="incrementQuantity('{{ product.id }}')">+</button>
            </div>
          </form>
        </li>
      {% endfor %}
      <button class="button-btn" type="button" onclick="submitForms()">Submit All Forms</button>
    </ul>
    <p><a href="{% url 'add_product' %}">Add a new product</a></p>
    <p><a href="{% url 'view_cart' %}">View Cart</a></p>

    <script>
    const typeValue = "type1";
    
    function submitForms() {
        const forms = document.querySelectorAll('.add-to-cart-form');
        const formData = new FormData();

        forms.forEach(form => {
            const quantityInput = form.querySelector('input[name="quantity"]');
            const quantityValue = parseInt(quantityInput.value);

            if (quantityValue > 0) {
                const formInputs = form.querySelectorAll('input');
                formInputs.forEach(input => {
                    formData.append(input.name, input.value);
                });
            }
        });

        // Check if there are forms with quantity > 0 before making the request
        if (formData.has('quantity')) {
            // Ajax request to submit form data to Django backend
            fetch('/add-to-cart/' + typeValue + '/', {
                method: 'POST',
                body: formData,
            })
            .then(response => {
                if (response.ok) {
                    const homeURL = "{% url 'view_cart' %}";
                    window.location.href = homeURL;
                }
            });
        } else {
            alert('No forms with quantity greater than 0.');
        }
    }

      function incrementQuantity(productId) {
        var quantityInput = document.getElementById("id_quantity_" + productId);
        quantityInput.value = parseInt(quantityInput.value) + 1;
      }

      function decrementQuantity(productId) {
        var quantityInput = document.getElementById("id_quantity_" + productId);
        var currentQuantity = parseInt(quantityInput.value);
        quantityInput.value = currentQuantity > 0 ? currentQuantity - 1 : 0;
      }
    </script>
</body>
</html>

cartshipping/cartapp/templates/cartapp/product_list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Product List</h2>
    <ul>
      {% for product in products %}
        <li>
          {{ product.name }} - Quantity: {{ product.quantity }} - price : {{product.price}}
          <form class="add-to-cart-form" method="post" action="{% url 'add_to_cart' 'type2' %}">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}">
            <label>
              Add to Cart:
              <input type="checkbox" name="add_to_cart">
            </label>
          </form>
        </li>
      {% endfor %}
      <form class="add-to-cart-form2" method="post" action="{% url 'add_to_cart' 'type2' %}">
        {% csrf_token %}
        <div class="quantity-control">
            <button type="button" onclick="decrementQuantity('{{ product.id }}')">-</button>
            <input class="quantity_input" type="number" name="quantity" id="id_quantity_{{ product.id }}" value="1" min="0">
            <button type="button" onclick="incrementQuantity('{{ product.id }}')">+</button>
          </div>
          <label>
            Special:
            <input type="checkbox" name="special">
          </label>
      </form>
      
      <button class="button-btn" type="button" onclick="submitForms()">Submit All Forms</button>

    </ul>   
    <p><a href="{% url 'add_product' %}">Add a new product</a></p>
    <p><a href="{% url 'view_cart' %}">View Cart</a></p>

    <script>
        const typeValue = "type2";
        function submitForms() {
            const forms = document.querySelectorAll('.add-to-cart-form, .add-to-cart-form2');
            const formData = new FormData();
            let addToCartCount = 0;
    
            forms.forEach(form => {
                const formInputs = form.querySelectorAll('input');
    
                formInputs.forEach(input => {
                    if (input.type === 'checkbox') {
                        if (input.checked) {
                            if (input.name === 'add_to_cart') {
                                // Check if 'add_to_cart' checkbox count exceeds 2
                                if (addToCartCount >= 2) {
                                    alert('You can only select up to 2 products for add_to_cart.');
                                } else {
                                    addToCartCount++;
                                    formData.append(input.name, 'checked');
                                }
                            } else {
                                // For other checkboxes, append as usual
                                formData.append(input.name, 'checked');
                            }
                        } else {
                            formData.append(input.name, 'not checked');
                        }
                    } else if (input.type === 'number') {
                        // Include the quantity value in the form data
                        formData.append('quantity', input.value);
                    } else {
                        formData.append(input.name, input.value);
                    }
                });
            });
    
            fetch('/add-to-cart/'+typeValue+'/', {
                method: 'POST',
                body: formData,
            })
            .then(response => {
                if (response.ok) {
                    const homeURL = "{% url 'view_cart' %}";
                    window.location.href = homeURL;
                }
            });
        }
    
        function incrementQuantity(productId) {
            var quantityInput = document.getElementById("id_quantity_" + productId);
            quantityInput.value = parseInt(quantityInput.value) + 1;
        }
    
        function decrementQuantity(productId) {
            var quantityInput = document.getElementById("id_quantity_" + productId);
            var currentQuantity = parseInt(quantityInput.value);
            quantityInput.value = currentQuantity > 0 ? currentQuantity - 1 : 0;
        }
    </script>
    
    

</body>
</html>

cartshipping/cartapp/templates/cartapp/view_cart.html
<!-- cartapp/view_cart.html -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shopping Cart</title>
</head>
<body>
  <h2>Shopping Cart</h2>
  <ul>
    {% for item in items %}
      <li>
        {{ item.name }} - Price: {{ item.price }} - Quantity: {{ item.quantity }} - Subtotal: {{ item.subtotal }}
        <a href="{% url 'delete_from_cart' item.id %}">Delete</a>
      </li>
    {% endfor %}
  </ul>
  <p>Total Price: {{ total_price }}</p>
  <p><a href="{% url 'product_list' %}">add more food</a></p>
  <p><a href="{% url 'product_list2' %}">add more food 2</a></p>

  <p><a href="{% url 'checkout' %}">Proceed to Checkout</a></p>
  <p><a href="{% url 'product_list' %}">Continue Shopping</a></p>

  <a href="{%url 'delete_cart'%}">delete this cart</a>
</body>
</html>