project_final/app/urls.py

from django.urls import path,include
from app.views import *

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('create/',AddFoodView.as_view(), name='create'),
    # path('managefood/',managefood,name='managefood'),
    # path('managefood/<str:date>/',managefood,name='managefood_add'),
    path('managefood/',ManageFoodView.as_view(),name='managefood'),
    path('managefood/<str:date>/',ManageFoodView.as_view(),name='managefood_add'),
    path('select_date/',select_date,name='select_date'),
    path('history_sale/',select_date,name='select_date'),
    path('clear_food/',clearfood,name='clear_food'),
    path('updatefood/<int:id>/',updatefood,name='updatefood'),
    path('delete/<int:id>/',delete, name='delete-food'),
    path('search/',search,name='search'),
    path('foodview/<int:id>/',foodview,name='foodview'),
    path('foodview/<int:id>/<str:target>/',foodview,name='sort_food'),
    # path('review/<int:id>/',reviewfood,name='review'),
    path('review/<int:id>/', ReviewFoodView.as_view(), name='review'),
    path('line-login/', line_login, name='line'),
    path('logout/', logout, name='logout'),
    path('login/callback/',line_callback,name='line_ callback'),
    path('about_us/',about_us,name='about-us'),
    # path('profile//',profile,name='profile_null'),
    # path('profile/<str:username>/',profile,name='profile'),
    path('profile//',ProfileView.as_view(), name='profile_null'),
    path('profile/<str:username>/',ProfileView.as_view(), name='profile'),
    # path('calendar/',calendar,name='calendar'),
    # path('calendar/<str:date>/<str:mark>/',calendar,name='calendar-date'),
    path('calendar/',CalendarView.as_view(),name='calendar'),
    path('calendar/<str:date>/<str:mark>/',CalendarView.as_view(),name='calendar-date'),
    # path('note/<str:date>/<str:type>/',note,name='note'),
    # path('note/<str:date>/<str:type>/<str:filter>/',note,name='note'),
    path('note/<str:date>/<str:type>/',AddTransactionView.as_view(),name='note'),
    path('note/<str:date>/<str:type>/<str:filter>/',AddTransactionView.as_view(),name='note'),
    path('delete_note/<str:date>/<str:type>/<int:id>/',delete_note,name='delete_note'),
    path('show_note/<str:date>/',show_note,name='show-note'),
    path('show_note/<str:date>/<str:type>/',show_note,name='show-note'),
    

    path('create_cart/', create_cart, name='create_cart'),
    path('view-cart/', view_cart, name='view_cart'),
    path('delete_cart/<str:code>/', delete_cart, name='delete_cart'),
    path('add-to-cart/<str:type>/', add_to_cart, name='add_to_cart'),
    path('add-to-cart/<str:type>/<str:modify>/', add_to_cart, name='add_to_cart'),
    path('shopping_food_type1/', shopping_food_type1, name='shopping_food1'),
    path('modify_cart1/<str:ref_code>/', modify_cart1, name='modify_cart1'),
    path('shopping_food_type2/', shopping_food_type2, name='shopping_food2'), 
    path('modify_cart2/<int:id>/', modify_cart2, name='modify_cart2'),
    path('cart/delete/<int:product_id>/<str:type>/', delete_from_cart, name='delete_from_cart'),
    # path('checkout/<str:ref_code>/<str:total_price>/', checkout, name='checkout'), 
    path('checkout/<str:ref_code>/<str:total_price>/', CheckoutView.as_view(), name='checkout'), 

    path('order_confirm/<str:ref_code>/', UserConfirmOrderView.as_view(), name='order_confirm'),
    # path('confirm_order/', admin_confirm_order, name='confirm_order'),
    # path('confirm_order/<str:filter>/',admin_confirm_order,name='sort_confirm_order'),
    # path('confirm_order/<str:code>/<str:status>/', admin_confirm_order, name='confirm_order'), 
    path('confirm_order/', AdminConfirmOrderView.as_view(), name='confirm_order'),
    path('confirm_order/<str:filter>/', AdminConfirmOrderView.as_view(),name='sort_confirm_order'),
    path('confirm_order/<str:code>/<str:status>/',  AdminConfirmOrderView.as_view(), name='confirm_order'), 
    path('complete_order/<str:ref_code>/',complete_order,name='complete_order'),
    path('history_confirm_order/',history_confirm_order,name='history_confirm_order'),
    path('history_confirm_order/<str:date>/',history_confirm_order,name='confirm_order_admin'),
    path('history_confirm_order/<str:date>/<str:filter>/',history_confirm_order,name='confirm_order_admin'),
    path('my_order/',my_order,name='my_order'),
    path('cancel_my_order/<str:ref_code>/',cancel_my_order,name='cancel_my_order'),
    # path('history_order/',my_history,name='my_history'),
    # path('history_order/<str:filter>/',my_history,name='my_history'),
    path('history_order/', MyHistoryView.as_view(), name='my_history'),
    path('history_order/<str:filter>/', MyHistoryView.as_view(), name='my_history'),
    path('qr_code/',qr_code,name='qr_code'),
    path('qr_code/<str:check>/',qr_code,name='qr_code'),
    path('next_qr_code/',next_qr_code,name='next_qr_code'),
    path('recommend_us/',recommend_us,name='recommend_us'),
    path('show_recommend_us/',show_recommend,name='show_recommend'),
    path('show_full_recommend/<str:id>/',full_recommend,name='full_recommend'),

    path('link_login/',before_login,name='before_login'),




] 

project_final/app/models.py
from datetime import date, datetime
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import time
import pytz

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email =models.EmailField(blank=True,null=True)
    first_name = models.CharField(max_length=100,blank=True,null=True)
    last_name = models.CharField(max_length=100,blank=True,null=True)
    line_id = models.CharField(max_length=500,blank=True,null=True)
    phone_number = models.CharField(max_length=10)
    picture = models.URLField(blank=True, null=True)
    age = models.CharField(max_length=20, choices=(
        ('ต่ำกว่า 19 ปี', 'ต่ำกว่า 19 ปี'),
        ('20-39 ปี', '20-39 ปี'),
        ('40-59 ปี', '40-59 ปี'),
        ('60 ปีขึ้น', '60 ปีขึ้น'),
    ), default='ต่ำกว่า 19 ปี') 
    gender = models.CharField(max_length=20, choices=(
        ('Male', 'ผู้ชาย'),
        ('Female', 'ผู้หญิง'),
        ('Other', 'อื่นๆ'),

    ), default='11-20') 
    def __str__(self) -> str:
        return f'{self.user} {self.email} '
    
class Food(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    unit = models.CharField(max_length=100,default='บาทต่อถุง')
    score = models.FloatField(default=0,blank=True,null=True)
    quantity_review = models.IntegerField(default=0,blank=True,null=True)
    # quantity_sale = models.IntegerField(default=0)
    image = models.ImageField(upload_to='media/image/',blank=True,null=True)

    def __str__(self) -> str:
        return f'เมนู {self.name} ราคา {self.price} บาท '
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height >300 or img.width >300:
                output_size = (300,300)
                img.thumbnail(output_size)
                img.save(self.image.path)
            
        
    
class Historysale(models.Model):
    date_field = models.DateField()
    food = models.ForeignKey(Food,on_delete=models.CASCADE,null=True,blank=True)
    quantity = models.IntegerField(default=0)
    OPTIONS = [
        ('ไม่ได้เลือก', 'ไม่ได้เลือก'),
        ('วางขาย', 'วางขาย'),
        ('ขายหมดแล้ว', 'ขายหมดแล้ว'),
    ]
    options = models.CharField(max_length=20, choices=OPTIONS,null=True) 
    def __str__(self) -> str:
        return f'{self.date_field} {self.food.name}'
    
    # @classmethod
    # def update_options_at_2pm(cls):
    #     current_time = timezone.now().time()
    #     if current_time == time(12, 0):  # 14:00 is 2 pm
            
    #         cls.objects.update(options=None)

class Reviewfood(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE)
    owner = models.ForeignKey(Member,on_delete=models.CASCADE,null=True)
    review = models.TextField(max_length=500,blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(choices=(
        (1, '1 ดาว'),
        (2, '2 ดาว'),
        (3, '3 ดาว'),
        (4, '4 ดาว'),
        (5, '5 ดาว'),

    ), default=5) 

    def __str__(self) -> str:
        return f'{self.food.name} rating : {self.rating}'

class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ('expenses', 'expenses'),
        ('income', 'income'),
        ('leftover','Leftover')
    ]
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0.0)
    amount = models.IntegerField(default=0)
    total_price =models.IntegerField(default=0)
    date = models.DateField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPES)


    def __str__(self) -> str:
        return f'{self.name} {self.date}'
    
class CancelReason(models.Model):
     reason = models.CharField(max_length=100)
     use_with = models.CharField(max_length=100)
     def __str__(self) -> str:
        return f'{self.reason} ถูกใช้กับ {self.use_with}'
class TimeReceive(models.Model):
     time_receive = models.CharField(max_length=100)
     def __str__(self) -> str:
        return f'{self.time_receive}'
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(null=True)  # Remove auto_now_add=True
    total_price = models.IntegerField(default=0)
    ref_code = models.CharField(max_length=100, null=True)
    checkout = models.BooleanField(default=False)
    TIME_CHOICES = [
        ('10:00 AM', '10:00 น.'),
        ('10:30 AM', '10:30 น.'),
        ('11:00 AM', '11:00 น.'),
        ('11:30 AM', '11:30 น.'),
        ('12:00 PM', '12:00 น.'),
        ('12:30 PM', '12:30 น.'),
        ('01:00 PM', '13:00 น.'),
        ('01:30 PM', '13:30 น.'),
    ]
    REASON = [
        ('soldout','สินค้าหมด'),
        ('cant-call-user','ไม่สามารถติดต่อลูกค้าได้'),
        ('user-dont-receive','ลูกค้าไม่มารับอาหาร'),
        ('user-cancel','ลูกค้าเปลี่ยนใจ/ยกเลิกการจอง'),
        ('cant-receive','ไม่สามารถไปรับอาหารได้'),
    ]
    time_receive = models.CharField(max_length=20, null=True,blank=True)
    cancel_reason = models.CharField(max_length=100,null=True,blank=True)
    confirm = models.CharField(max_length=20, choices=(
        ('wait_to_confirm', 'รอยืนยัน'),
        ('confirmed', 'ยืนยันเเล้ว'),
        ('cancel', 'ยกเลิก'),
    ), default='wait_to_confirm')
    completed = models.CharField(max_length=20, choices=(
        ('incompleted', 'ยังไม่สมบุรณ์'),
        ('completed', 'สมบุรณ์'),
    ), default='incompleted')

    

    def save(self, *args, **kwargs):
        if not self.created_at:
            thai_tz = pytz.timezone('Asia/Bangkok')
            utc_now = timezone.now()
            self.created_at = utc_now.astimezone(thai_tz)
        super().save(*args, **kwargs)
        
    def __str__(self) -> str:
        return f'{self.ref_code} confirm {self.confirm}'
class OrderItemtype1(models.Model):
    # user = models.ForeignKey(User,on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food = models.ForeignKey(Food,on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.food} price {self.total_price}'
    
class OrderItemtype2(models.Model):
    # user = models.ForeignKey(User,on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=100,null=True)
    foods = models.ManyToManyField('Food')
    quantity = models.IntegerField()
    price = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.name} price {self.total_price}'
    
class RecommendUs(models.Model):
    user = models.ForeignKey(Member,on_delete=models.SET_NULL,null=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} {self.created}'
    

project_final/app/templates/app/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
    <style>
        body {
            background-color: #f5f5f7;
        }
        /* set container เพื่อให้ไปอยูาตรงกลาง สำหรับ form  */
        .container  {
            display: flex;
            /* border: 1px solid red; */
            justify-content: center;
            align-items: center;
            height: 70vh;
        }
         /* ตั้งค่า form (กล่องของ form ใหญ่) */
        .form-data {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid  #ccc;
            padding: 20px;/*ขนาดของกลาง form-data ให้มรขนาดช่วงว่างเยอะขึ้น */
            border-radius: 10px; /*ทำให้มุมมนไม่เหลี่ยม */
            background-color: #f9f9f9;
        }
        .form-detail {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-between;
        }

        .form_data {
            flex: 1;
            margin-right: 20px;
        }

        .form_image {
            flex: 1;
        }

        .form_data div {
            margin-bottom: 10px;
        }

        /* Beautify form fields */
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        input[type="file"] {
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            width: calc(100% - 10px); /* Adjust the width to align properly */
            margin-bottom: 10px;
        }

        input[type="submit"] {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            width: 100%;
        }
    </style>
</head>
<body>
    {% include 'app/navbar.html' %}
    <div class="container">
        <form action="/create/" method="post" enctype="multipart/form-data" class="form-data">
            {%csrf_token%}
            <div class="form-detail">
        
                <div class="form_data">
                    <div class="food_name">
                        <label for="id_name">name</label>
                        <input type="text" name="name" step="any" required id="id_name">
                    </div>
                    <div class="food_price">
                        <label for="id_price">price</label>
                        <input type="number" name="price" step="any" required id="id_price">
                    </div>
                    <div class="food_unit">
                        <label for="id_unit">หน่วย</label>
                        <input type="text" name="unit" step="any" required id="id_unit" value="บาทต่อถุง">
                    </div>
                </div>

            </div>
            
            <div class="form_image">
                <div class="upload_image">
                    <label for="id_image"></label>
                    <input type="file" name="image" required id="id_image">
                </div>
            </div>
            <input type="submit" value="submit">
            

        </form>
        
    </div>

</body>
</html>

project_final/app/templates/app/navbar.html

<style>
     body {
            margin: 0;
            padding: 0;
        }
        .navbar {
            display: flex;
            height: 70px;
            background-color: #333;
            justify-content: space-between;
            align-items: center;

  
        }
        ul {
            display: flex;
            list-style: none;
        }
        ul li {
            margin: 3 lr;
            
        }
        ul li a,.login-btn,.logout-btn {
            color: aliceblue;
            text-decoration: none;
            

        }
        .leftitem {
            display: flex;
            width: 750px;
            /* border: 1px solid burlywood; */

        }
        .logoitem {
            margin-left: 20px;
            display: flex;
            width: 170px;
            margin-right: 20px;
            /* border: 1px solid palegreen; */

        }
        .res_name a {
            font-size: 20px;
        }
        .search-btn-about {
            display: flex;
            align-items: center;
            justify-content: space-between;
            /* border: 1px solid tomato; */

        }
        div li {
            list-style: none;
        }
        div li a {
            color: aliceblue;
            text-decoration: none; 
            margin-left:30px ;
        }
        div h1 a {
            color: aliceblue;
            text-decoration: none;
            list-style: none;
        }
        .searchbar {
            display: flex;
            align-items: center;
            /* border: 1px solid tomato; */
        }
        .search-box {
            border-radius: 0.5rem;
            height: 30px;
        }
        .search button {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            height: 30px; 
            margin-left: 5px; 
            font-size: small;
            line-height: 10px;
        }

        .leftitem form {
            display: flex;
            align-items: center;

        }
        .rightitem {
            display: flex;
            width: 250px;
            margin-right: 340px;
            /* border: 1px solid red; */
     
        }
        .box-profile,.create_cart,.box-history {
            display: flex;
            align-items: center;
            

        }
        .username-btn {
            display: flex;
            align-items: center;
            margin-right: 20px;
            color: #3498db;
            width: 60px;
            /* border: 1px solid red; */
        }

        .about-us,.profile,.login-btn,.logout-btn,.cart,.history-btn,.recommend-us {
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 4px;
            background-color: #333;
            border: none;
            color: #FFFFFF;
            text-align: center;
            padding: 15px;
            height: 3px;
            margin: 5px;
            text-decoration: none;
        }
        .about-us,.profile,.login-btn,.logout-btn,.cart,.recommend-us {
            width: 70px;
        }
        .recommend-us {
            font-size: 14px;
        }
        .history-btn {
            width: 90px;
        }
        .about-us:hover,.profile:hover,.login-btn:hover,.logout-btn:hover,.cart:hover,.history-btn:hover,.recommend-us:hover {
            border-radius: 4px;
            border: none;
            color: #FFFFFF;
            text-align: center;
            padding: 15px;
            height: 3px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
        }
        .about-us:hover,.profile:hover,.login-btn:hover,.logout-btn:hover,.cart:hover,.recommend-us:hover {
            width: 70px;
        }
        .history-btn:hover {
            width: 90px;
        }
        .about-us:hover,.profile:hover,.login-btn:hover{
            background-color: #1E8FF4;
    }
        .recommend-us:hover {
            background-color: #F41E96;

    }
        .cart:hover {
            background-color: #F4891E;
        }
        .logout-btn:hover {
            background-color: #f4511e;

        }
        .history-btn {
            font-size: 14px;

        }
        .history-btn:hover{
            background-color: #6A4DF9;
        }
</style>
<header>
    <nav class="navbar">
        <div class="leftitem">
            <div class="logoitem">
                <h1 class="res_name"><a href="{%url 'home'%}">ร้านข้าวแกงก็อปปี้</a></h1>
            </div>
            <div class="search-btn-about">
                <form class="search" method="post" action="/search/">
                    {%csrf_token%}
                    <div class="searchbar">
                        <input class="search-box" type="search" aria-label="Search" name="text-search">
                        <button type="submit">Search</button>
                    </div>
                </form>
                <a class="about-us" href="/about_us/">about us</a>

                {% if request.user.is_superuser %}
                <a class="recommend-us" href="{%url 'see_all_data'%}">Dashboard</a>
                {%else%}
                <a class="recommend-us" href="/recommend_us/">ข้อเสอแนะ</a>
                {% endif %}

            </div>
        </div>

        

        <div class="rightitem">
            <div class="box-history">
                <a class="history-btn" href="/my_order/">ออเดอร์ของฉัน</a>
            </div>
            <div class="box-profile">
                <a class="profile" href="/profile/{{user.username}}/">Profile</a>
            </div>
            <div class="create_cart">
                <a class="cart" href="/create_cart/">Shopping</a>

            </div>
            <ul class="box-login">
                {% if user.is_authenticated %}
                <span class="username-btn">{{ user.username }}</span>
                <a class="logout-btn" 
                href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="login-btn" href="/link_login/">Login</a>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

project_final/app/templates/app/order_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    body {
            background-color: #f5f5f7;
        }
    .container {
      display: flex;
      /* border: 1px solid red; */
      margin: 5px;
      justify-content: center;
    }
    .box-container {
      display: flex;
      /* border: 1px solid blue;  */
      height: 200px;
      width: 500px;
      justify-content: center;
      align-items: center;
      background-color: #FDFDFD;
      box-shadow: transparent 0 0 0 3px,rgba(18, 18, 18, .1) 0 6px 20px;
      margin-top: 40px;

    }
    .thank-text {
      font-size: 28px;
      margin-bottom: 10px;
    }
    .box-signal {
      display: flex;
      justify-content: center;
      margin-bottom: 10px;
    }
    .signal-thank {
      height: 60px;
      width: 60px;
      color: red;
    }
    .box-btn {
      display: flex;
      justify-content: center;
    }
    .btn-back-home {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100px;
      height: 40px;
      border-radius: 4px;
      text-decoration: none;
      color: white;
      border: 1px solid #F94D4D;
      background-color: #F94D4D;
    }
  </style>
</head>
<body>
  {% include 'app/navbar.html' %}
  <div class="container">
    <div class="box-container">
      <div class="box-content">
        <div class="thank-text">
          Thank you for your order
        </div>
        <div class="box-signal">
          <div class="signal-thank">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>          
          </div>
        </div>
        <div class="box-btn">
          <a class="btn-back-home" href="{% url 'home' %}">back to home</a>
        </div>

      </div>
    </div>
  </div>
</body>
</html>

project_final/app/templates/app/updatefood.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
    <style>
        .main-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-direction: row;
            margin: 20px;
            width: 1200px;
        }
        /* set container เพื่อให้ไปอยูาตรงกลาง สำหรับ form  */
        .container  {
            display: flex;
            /* border: 1px solid red; */
            justify-content: center;
            align-items: center;
            height: 70vh;
            width: 400px;
            flex-direction: row;
            margin-left: 400px;
        }
         /* ตั้งค่า form (กล่องของ form ใหญ่) */
        .form-data {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 80%;
            border: 1px solid  #ccc;
            padding: 20px;/*ขนาดของกลาง form-data ให้มรขนาดช่วงว่างเยอะขึ้น */
            border-radius: 10px; /*ทำให้มุมมนไม่เหลี่ยม */
            background-color: #f9f9f9;
        }
        .form-detail {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-between;
        }

        .form_data {
            flex: 1;
            margin-right: 20px;
        }

        .form_image {
            flex: 1;
        }

        .form_data div {
            margin-bottom: 10px;
        }

        /* Beautify form fields */
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        input[type="file"] {
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            width: calc(100% - 10px); /* Adjust the width to align properly */
            margin-bottom: 10px;
        }

        .button-btn {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            width: 100%;
        }

        .delete-btn {
            display: flex;
            justify-content: center;
            align-items: center;
            border: 1px solid red;
            margin-top: 20px;
            width: 100%;
            height: 30px;
            border-radius: 4px;
            background-color: #F94D4D;
            text-decoration: none;
            color: white;
        }
        img {
            border-radius: 0.5rem;
            border: 1px solid black;

        }
        .message-alerts {
            display: flex;
            align-items: center;
            width: 100%;
            justify-content: center;
            margin-top: 10px;
        }
        .error {   
            display: flex;
            width: 80%;  
            height: 40px;
            align-items: center;
            justify-content: space-between;
            color: #000000;
            font-weight: bold;
            font-size: 18px;
            background-color: #F97979;
            border: 1px solid #F97979;
            padding: 0 10px; 
            box-sizing: border-box; 
            border-radius: 0.3rem;
        }
        .box_error {
            display: flex;
            /* border: 1px solid blue; */
            justify-content: end;
            width: 90%;

        }
        .error .close-button {
            cursor: pointer;
            margin-left: 100px;
        }
    </style>
</head>
<body>
    {% include 'app/navbar.html' %}
    {% if messages %}
    <div class="message-alerts">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="error">
                    <div class="box_error">
                        {{ message }}
                    </div>
                    <span class="close-button" onclick="this.parentElement.style.display='none';">&times;</span>
                </div>
            {% elif message.tags == 'success' %}
                <div class="success">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="main-container">
        <div class="container">
            <form action="/updatefood/{{food.id}}/" method="post" enctype="multipart/form-data" class="form-data">
                {%csrf_token%}
                <div class="form-detail">
            
                    <div class="form_data">
                        <div class="food_name">
                            <label for="id_name">name</label>
                            <input type="text" name="name" step="any" required id="id_name" value="{{form.instance.name}}">
                        </div>
                        <div class="food_price">
                            <label for="id_price">price</label>
                            <input type="number" name="price" step="any" required id="id_price" value="{{form.instance.price}}">
                        </div>
                        <div class="food_unit">
                            <label for="id_unit">หน่วยต่อถุง</label>
                            <input type="text" name="unit" step="any" required id="id_unit" value="{{form.instance.unit}}">
                        </div>
                    </div>

                </div>
                
                <div class="form_image">
                    <div class="upload_image">
                        <label for="id_image"></label>
                        <!-- <img src="{{form.instance.image.url}}" alt="food-image"> -->
                        <!-- <input type="text" name="image_url" id="id_image" value="{{form.instance.image.url}}"> -->
                        <input type="file" name="image">
                    </div>
                </div>
                <input class="button-btn" type="submit" value="submit">
                <a class="delete-btn" href="/delete/{{food.id}}/">delete</a>

            </form>
            
        </div>
        <div class="container-image">
            <div class="image-area">
                <img src="{{form.instance.image.url}}" alt="food-image">
            </div>
        </div>
    </div>
</body>
</html>